import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { UserDict } from "../interfaces/socket";

// Define the interface for the state
interface PairedUserState {
    user: UserDict | null
    
}
  
  // Set the initial state
const initialState: PairedUserState = {
    user: null,
};

// Create a Redux Toolkit slice
const pairedUserSlice = createSlice({
  name: "pairedUser",
  initialState,
  reducers: {
    // Reducer function for handling the "receiveChatMessage" action
    receiveUser: (state, action: PayloadAction<UserDict>) => {
      state.user = action.payload;
    },
    clearUser: (state) => {
      state.user = null;
    },
  },
});

// Export the action creator generated by createSlice
export const { receiveUser, clearUser } = pairedUserSlice.actions;

// Export the reducer generated by createSlice
export default pairedUserSlice.reducer;