"""empty message

Revision ID: 869a7c68d07f
Revises: f0040eb93e96
Create Date: 2024-03-22 12:48:01.300868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869a7c68d07f'
down_revision = 'f0040eb93e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends_association', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='friendshipstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends_association', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='friendshipstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
